export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const UPDATE_COORDINATES = 'UPDATE_COORDINATES';
export const DEFAULT_COORDINATES = 'DEFAULT_COORDINATES';
export const MARKER_TOGGLE = 'MARKER_TOGGLE';