export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const UPDATE_COORDINATES = 'UPDATE_COORDINATES';
export const DEFAULT_COORDINATES = 'DEFAULT_COORDINATES';
export const SET_MARKER = 'SET_MARKER';
export const MARKER_DESC = 'MARKER_DESC';